theme = "my_theme"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
scrolloff = 8
color-modes = true
true-color = true
undercurl = true
# these are the engram kb layout homerow keys, which I use
jump-label-alphabet = "sitehancrkmjludowyvbfxpg"
end-of-line-diagnostics = "hint"
rulers = [80, 120]

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name", "version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
goto-reference-include-declaration = false
display-inlay-hints = true
display-progress-messages = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
H = ":buffer-previous"
L = ":buffer-next"
X = "select_line_above"
C-h = "jump_view_left"
C-l = "jump_view_right"
C-k = "jump_view_up"
C-j = "jump_view_down"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
f = "goto_word"
G = "goto_file_end"

[keys.insert]
C-h = ["jump_view_left", "insert_mode"]
C-l = ["jump_view_right", "insert_mode"]
C-k = ["jump_view_up", "insert_mode"]
C-j = ["jump_view_down", "insert_mode"]
S-tab = "move_parent_node_start"
C-f = "goto_word"

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
f = "extend_to_word"
X = "select_line_above"
G = "goto_file_end"

[keys.normal.space]
space = "file_picker"

[keys.normal.backspace]
backspace = "suspend"
b = ":buffer-close"
w = "wclose"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline
