theme = "my_theme"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
scrolloff = 8
color-modes = true
true-color = true  
undercurl = true
# these are the engram kb layout homerow keys, which I use
jump-label-alphabet = "hatesincludorkmjfxwypgvb"
end-of-line-diagnostics = "hint"
rulers = [80, 120]

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name", "version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
goto-reference-include-declaration = false
display-inlay-hints = true
display-progress-messages = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
H = ":buffer-previous"
L = ":buffer-next"
X = "select_line_above"
C-h = "jump_view_left"
C-l = "jump_view_right"
C-k = "page_cursor_half_up"
C-j = "page_cursor_half_down"
ret = "goto_word"

# Match in next instance of pair
[keys.normal.m.n]
"(" = "@s\\(<ret>nmim"
"{" = "@s\\{<ret>nmim"
"[" = "@s\\[<ret>nmim"
'"' = '@s\"<ret>nmim'
"'" = "@s\\'<ret>nmim"
"<" = "@s<lt><ret>nmim"

# Match in previous instance of pair
[keys.normal.m.p]
"(" = "@s\\)<ret>Nmmmim"
"{" = "@s\\}<ret>Nmmmim"
"[" = "@s\\]<ret>Nmmmim"
'"' = '@s\"<ret>Nmmmim'
"'" = "@s\\'<ret>Nmmmim"
"<" = "@s<gt><ret>Nmmmim"

[keys.insert]
C-h = ["jump_view_left", "insert_mode"]
C-l = ["jump_view_right", "insert_mode"]

[keys.select]
ret = "extend_to_word"
X = "select_line_above"

[keys.normal.space]
space = "file_picker"

[keys.normal.backspace]
backspace = "suspend"
# Yazi
e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ':set mouse false',
  ':set mouse true',
]
# Lazygit
g = [
  ":write-all",
  ":insert-output lazygit >/dev/tty",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
  ":reload-all"
]
# k9s
k = [
  ":write-all",
  ":insert-output k9s >/dev/tty",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
  ":reload-all"
]

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline
