theme = "tokyonight"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
scrolloff = 8
color-modes = true
true-color = true  
undercurl = true
# these are the engram kb layout homerow keys, which I use
jump-label-alphabet = "hatesincludorkmjfxwypgvb"
end-of-line-diagnostics = "error"
rulers = [80, 120]
completion-replace = true
popup-border = "all"
rainbow-brackets = true

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name", "version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
goto-reference-include-declaration = false
display-inlay-hints = true
display-progress-messages = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.smart-tab]
supersede-menu = true

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[keys.normal]
X = "select_line_above"
C-h = "jump_view_left"
C-l = "jump_view_right"
C-k = "page_cursor_half_up"
C-j = "page_cursor_half_down"
ret = "goto_word"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

[keys.insert]
C-h = ["jump_view_left", "insert_mode"]
C-l = ["jump_view_right", "insert_mode"]
S-tab = "move_parent_node_start"

[keys.select]
ret = "extend_to_word"
X = "select_line_above"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"

[keys.normal.backspace]
w = ":write-all"
r = [":reload-all", ":config-reload"]
# Yazi
e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ':set mouse false',
  ':set mouse true',
]
# Lazygit
g = [
  ":write-all",
  ":insert-output lazygit >/dev/tty",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
  ":reload-all"
]
# k9s
k = [
  ":write-all",
  ":insert-output k9s >/dev/tty",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
  ":reload-all"
]

