theme = "my_theme"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
scrolloff = 8
color-modes = true
true-color = true
# these are the engram kb layout homerow keys, which I use
jump-label-alphabet = "sitehancrkmjludowyvbfxpg"
end-of-line-diagnostics = "hint"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
H = ":buffer-previous"
L = ":buffer-next"
C-h = "jump_view_left"
C-l = "jump_view_right"
C-k = "jump_view_up"
C-j = "jump_view_down"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
A-f = "goto_word"

[keys.insert]
C-h = ["jump_view_left", "insert_mode"]
C-l = ["jump_view_right", "insert_mode"]
C-k = ["jump_view_up", "insert_mode"]
C-j = ["jump_view_down", "insert_mode"]
S-tab = "move_parent_node_start"
A-f = "goto_word"

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
A-f = "extend_to_word"

[keys.normal.space]
space = "file_picker"
f = ":format"
w = ":w"
W = ":wa"
x = ":q"
X = ":qa"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline
